### ISSUE TITLE
configuring sonar.properties

### ISSUE THREAD

**Issue by bdito** [bitnami/bitnami-docker-sonarqube#1]
I have to configure LDAP in "sonar.properties".
Persisting the file "/opt/bitnami/sonarqube/conf/sonar.properties" in the container to the host system via docker volumes gets the following error:
`Error executing 'postInstallation': File /opt/bitnami/sonarqube/conf/sonar.properties did not match any of the provided substitutions`

Is there a way to configure things like LDAP in "sonar.properties" like with environment variables?

**Comment by tompizmor** [comment]
> Is there a way to configure things like LDAP in "sonar.properties" like with environment variables?

No. Right now is not possible to do it. 

I think you could just start the container with the default configuration, exec into the container, edit the configuration and restart the sonarqube service with this command:

```
nami restart sonarqube
```

**Comment by CayoM** [comment]
> > Is there a way to configure things like LDAP in "sonar.properties" like with environment variables?
> 
> No. Right now is not possible to do it.
> 
> I think you could just start the container with the default configuration, exec into the container, edit the configuration and restart the sonarqube service with this command:
> 
> ```
> nami restart sonarqube
> ```

this is pretty much useless, since if you drop the container those changes are gone.

Since im having the same problem trying to use "sonar.web.context" in order to use Sonar together with Traefik and have clean URL contexts, I think it can be accomplished by changing for ex.

bitnami-docker-sonarqube/7/debian-9/rootfs/sonarqube-inputs.json

by including something like:

  "context": "{{$global.env.SONARQUBE_CONTEXT}}"

and using it as an ENV variable in the docker run/compose.

However im not sure how it is mapped to the actual sonar.properties file... maybe there is another change needed in this case.

Can you please guide on how to accomplish it? Maybe we can create a pull request then.

TIA

**Comment by tompizmor** [comment]
> this is pretty much useless, since if you drop the container those changes are gone.

Yes, you are right about that. 

> However im not sure how it is mapped to the actual sonar.properties file... maybe there is another change needed in this case.

That logic is inside the nami module. However, the code is not publicly available on GitHub so I am afraid you won't be able to send a PR.

We will work on adding a SONARQUBE_WEB_CONTEXT env var and let you know once the new container is released.

**Comment by fcappi** [comment]
+1

**Comment by fcappi** [comment]
If you are deploying the container to a K8 cluster, a workaround to configure sonar properties would be to use postStart lifecycle

```
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                # Wait for the container entrypoint to setup sonar
                until [ -f /opt/bitnami/sonarqube/conf/sonar.properties ]; do
                  echo "Waiting for sonar setup before editing properties (Sleeping for 5 seconds)"
                  sleep 5
                done

                # Adding custom properties to sonar
                cat <<EOT >> /opt/bitnami/sonarqube/conf/sonar.properties
                my.sonar.property=property_value
                EOT
```

**Comment by tompizmor** [comment]
Thanks for the suggestion @fcappi! It can be a valid option until we release a version including the new env var.

**Comment by tompizmor** [comment]
@CayoM @fcappi We just released SonarQube with SONAQUBE_WEB_CONTEXT environment variable support.
You can take a look at the env vars section in the [README](https://github.com/bitnami/bitnami-docker-sonarqube#environment-variables)

**Comment by fcappi** [comment]
@tompizmor It seems like the new env variable solves the issue related by @CayoM , but not the initial issue related by @bdito .

It would be great if we could override any sonar property instead of only specific ones like SONARQUBE_WEB_CONTEXT.

Maybe something like:

SONAR_PROPERTIES="my.sonar.property1=property_value my.sonar.property2=property_value my.sonar.propertyN=property_value"

And then these properties are just appended to the sonar.properties file.

**Comment by tompizmor** [comment]
@fcappi Yes, that is right! Thanks for the suggestion. 
We should also probably support mounting the whole configuration file in case it is not possible yet.

I will create a task so we evaluate and include this feature on future releases.

**Comment by fcappi** [comment]
@tompizmor That would be even better. Great, thanks!

**Comment by tompizmor** [comment]
Thanks for showing interest @skooter777. We will take it into account in order to prioritize our feature request tasks.

**Comment by robincher** [comment]
Will love to have this feature too,thank you.

**Comment by jfmercer** [comment]
Like @robincher and @fcappi, I too would like to use environment variables to edit `sonar.properties`.

**Comment by andresbono** [comment]
Hi @jfmercer, @robincher, thanks for letting us know. I will forward your interests to the appropriate team.

**Comment by chovy** [comment]
I'm getting this original error too. docker-compose up --build throws an error.

I changed port to 9000 and nothing is listening there.

**Comment by andresbono** [comment]
Hi @chovy, can you give us more details on how are you launching the docker-compose? Are you mounting the configuration file? Can you share your docker-compose?

**Comment by joubbi** [comment]
I would like to modify `sonar.properties` as well. Just like @bdito I want to authenticate my SonarQube users with LDAP.
Is it possible to get a time estimate of the fix for this issue?

**Comment by andresbono** [comment]
Hi @joubbi, I have increased the priority of the internal task that we have to address this issue. However, I can't give you an ETA for the feature.

We will update this issue as soon as we have more news.

**Comment by carrodher** [comment]
Hi all, we just released a new version with the possibility of specifying different sonarqube properties via an environment variable.

You can set the `SONARQUBE_PROPERTIES` env. variable that is a comma separated list of properties to be set in the _sonar.properties_ file, i.e `my.sonar.property1=property_value,my.sonar.property2=property_value`. By default this variable is empty.

As a functional example, I added the following to the _docker-compose.yaml_:
```yaml
environment:
  ...
  - SONARQUBE_PROPERTIES=sonar.jdbc.maxWait=4000,sonar.jdbc.minIdle=3
```
deploying the docker-compose with the above env. variable and comparing it with another installation without the env. variable those are the differences in the _sonar.properties_:
```diff
66c68
- #sonar.jdbc.minIdle=2
+ sonar.jdbc.minIdle = 3
71c73
- #sonar.jdbc.maxWait=5000
+ sonar.jdbc.maxWait = 4000
```

The properties set in the env. variable are applied to the file.

You can find those changes from the following tags:
- `7-debian-10`, `7.9.3-debian-10-r89`, `7`, `7.9.3`, `latest`
- `8-debian-10`, `8.3.1-debian-10-r31`, `8`, `8.3.1`

**Comment by Catscrash** [comment]
Hi,

I'm having an issue with this. I'm trying to use

sonarqube:
    image: docker.io/bitnami/sonarqube:8-debian-10

with the settings:
`
- SONARQUBE_PROPERTIES=sonar.security.realm=LDAP,ldap.servers=server1,server2,ldap.server1.url="ldaps://serverurl1:3269",ldap.server2.url="ldaps://serverurl2:3269",ldap.bindDn="CN=sonarqube,OU=Service Accounts,OU=XXX,DC=XXX,DC=XXX,DC=XXX",ldap.bindPassword=XXXXX
`

When I docker-compose up the file, I get the error:

sonarqube_1   | sonarqu INFO  ==> Using properties provided by SONARQUBE_PROPERTIES env. variable...
sonarqube_1   | Error executing 'postInstallation': File /opt/bitnami/sonarqube/conf/sonar.properties did not match any of the provided substitutions

Without the setting it starts up fine. Any idea what might be the reason?

thanks

**Comment by andresbono** [comment]
Hi @Catscrash, as per @carrodher comment https://github.com/bitnami/bitnami-docker-sonarqube/issues/1#issuecomment-651736277:

> env. variable that is a comma separated list of properties

In your case, some property values contain commas, for instance `ldap.servers=server1,server2`. That's probably causing issues. In addition to that, all the property keys should exist in the file. You can see the contents by executing:

```
docker run --rm bitnami/sonarqube cat /opt/bitnami/sonarqube/conf/sonar.properties
```

Can you check if you can avoid using commas in the values?

**Comment by Catscrash** [comment]
Hi @andresbono I removed server1,server2 and just used ldap.url, but I have no way to remove the commas in ldap.bindDn e.g. - as this has always commas, I don't see a way to specify that without commas

**Comment by andresbono** [comment]
Thanks for checking, @Catscrash. In that case, could you try an alternative approach and mount the file as a volume?
