### ISSUE TITLE
Error executing 'postInstallation': You should specify user, password and name parameters for the database creation

### ISSUE THREAD

**Issue by kabo** [bitnami/bitnami-docker-sonarqube#11]
**Description**

I'm unable to create a database as described in https://github.com/bitnami/bitnami-docker-sonarqube#create-a-database-for-sonarqube-using-postgresql-client

**Steps to reproduce the issue:**

```
docker run \
  -e POSTGRESQL_HOST=some.db.host \
  -e POSTGRESQL_ROOT_USER=root \
  -e POSTGRESQL_ROOT_PASSWORD=xxx \
  -e POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sq \
  -e POSTGRESQL_CLIENT_CREATE_DATABASE_USER=sq \
  -e POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=xxx \
  -e ALLOW_EMPTY_PASSWORD=no \
  -e NAMI_LOG_LEVEL=trace \
  bitnami/sonarqube:latest
```

**Describe the results you received:**

```
Welcome to the Bitnami sonarqube container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues

nami    INFO  Initializing postgresql-client
Error executing 'postInstallation': You should specify user, password and name parameters for the database creation
nami    TRACE Error: Error executing 'postInstallation': You should specify user, password and name parameters for the database creation
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.postgresql-client/main.js:64:11)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
    at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:524:30)
    at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:748:14)
```

**Describe the results you expected:**

The script to connect to the PGSQL and create the database and user.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 23
 Server Version: 19.03.1
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-5-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.58GiB
 Name: esk
 ID: NFZQ:ZPFD:V3Z2:BKQQ:CNZ6:KGMI:R4CV:4TZG:M3ST:DXBR:A7AM:DJ7V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by kabo** [comment]
Ah, found the error. The README says `POSTGRESQL_CLIENT_CREATE_DATABASE_USER`, but the dockerfile has `POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME` (https://github.com/bitnami/bitnami-docker-sonarqube/blob/7.9.1-debian-9-r20/7/debian-9/Dockerfile#L16)

Setting `POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME` works.
BTW, according to the dockerfile, `POSTGRESQL_ROOT_USER` defaults to `postgres` (https://github.com/bitnami/bitnami-docker-sonarqube/blob/7.9.1-debian-9-r20/7/debian-9/Dockerfile#L20) not `root` as described in the README.

**Comment by andresbono** [comment]
Hi @kabo, thanks for noticing. We will apply your suggestions shortly.

**Comment by marcosbc** [comment]
Hi @kabo, just wanted to let you know we implemented the change in the README. Thanks for reporting this!

**Comment by fanefknroo** [comment]
so basically there is no id=1 

`bitnami_sonarqube=> SELECT created_at FROM properties WHERE id=1;
 created_at
------------
(0 rows)

bitnami_sonarqube=> SELECT * FROM properties WHERE id=1;
 id | prop_key | resource_id | user_id | is_empty | text_value | clob_value | created_at
----+----------+-------------+---------+----------+------------+------------+------------
(0 rows)

bitnami_sonarqube=> SELECT * FROM properties WHERE id=1;
 id | prop_key | resource_id | user_id | is_empty | text_value | clob_value | created_at
----+----------+-------------+---------+----------+------------+------------+------------
(0 rows)

bitnami_sonarqube=>
bitnami_sonarqube=> SELECT * FROM properties;
 id  |               prop_key               | resource_id | user_id | is_empty |                                   text_value                                    | clob_value |  created_at
-----+--------------------------------------+-------------+---------+----------+---------------------------------------------------------------------------------+------------+---------------
   2 | sonar.core.id                        |             |         | f        | xxxxxxxxxxxxx                                                  |            | 1565075045312
   3 | sonar.forceAuthentication            |             |         | f        | true                                                                            |            | 1565075045256
  11 | sonar.cpd.exclusions                 |        4358 |         | f        | build/**                                                                        |            | 1568229894225
 181 | sonar.core.startTime                 |             |         | f        | 2019-09-20T11:02:51+0000                                                        |            | 1568977371787
  15 | sonar.coverage.exclusions            |             |         | f        | build/**,target/**                                                              |            | 1568230082255
bitnami_sonarqube=> SELECT * FROM properties WHERE id=1;
 id | prop_key | resource_id | user_id | is_empty | text_value | clob_value | created_at
----+----------+-------------+---------+----------+------------+------------+------------
(0 rows)

bitnami_sonarqube=> update properties set id=1 WHERE id=2;
UPDATE 1
bitnami_sonarqube=> SELECT created_at FROM properties WHERE id=1;
  created_at
---------------
 1565075045312
(1 row)`

and now it starts

**Comment by jfmontanaro** [comment]
Just wanted to let you all know this seems to have snuck back in via https://github.com/bitnami/bitnami-docker-discourse/commit/6f0941b03385f891687ea500ebfab171d96792c6, same fix as before.
