### ISSUE TITLE
Doesn't start after upgrade from 7 to 8

### ISSUE THREAD

**Issue by kabo** [bitnami/bitnami-docker-sonarqube#20]
**Description**

We're running version 7-debian-9 and want to upgrade to 8-debian-10. But when we try to start the docker image it just stops abrubtly. Please see attached [log](https://github.com/bitnami/bitnami-docker-sonarqube/files/4491571/sq.log).

**Steps to reproduce the issue:**

1. Set up SonarQube with 7-debian-9
2. Stop the container
3. Start SonarQube with 8-debian-10
4. Container stops

**Describe the results you received:**

Container stops

**Describe the results you expected:**

Container to run

**Additional information you deem important (e.g. issue happens only occasionally):**

This is running in AWS ECS Fargate

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Note that you are doing an upgrade between major versions. That means that the process is highly likely not straightforward. From what I read in the documentation, you would have to re-import all of the projects even if you try to upgrade. Would it make sense for your case to start with a fresh Sonarqube 8 container and re-import all of your projects? 

https://docs.sonarqube.org/latest/setup/upgrading/

**Comment by kabo** [comment]
I couldn't find anything about having to re-import the projects in that page, but this is relevant:
> If you're using non-default plugins, they need to be manually added to the new sonarqube_extensions_8_x volume after the first start-up only.

I'll try an image without extra plugins.

**Comment by kabo** [comment]
No difference, I may need to try and run this locally to figure out what's going on.

**Comment by kabo** [comment]
I made two changes to my container definition and it started running.

```
[{
    "environment": [
      {
        "name": "SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS",
        "value": "-Dnode.store.allow_mmapfs=false -Dnode.store.allow_mmap=false"
      }
    ],
    "ulimits": [
      {
        "name": "nofile",
        "softLimit": 65535,
        "hardLimit": 65535
      },
      {
        "name": "memlock",
        "softLimit": -1,
        "hardLimit": -1
      }
    ]
}]
```

I was able to go to `/setup` and upgrade the database. But after stopping and starting the container again it won't start up any longer. This time the error is

```2020.04.17 10:26:52 WARN app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1```

**Comment by kabo** [comment]
OK, removing `node.lock` from `sonarqube/data/es6/nodes/0` helped, now it's starting again.

This container can disappear abruptly and will not be able to remove `node.lock`. Is there a way to ignore that file?

**Comment by kabo** [comment]
After running
```sh
chmod 777 /bitnami/sonarqube/data/es6/nodes/0
chmod 666 /bitnami/sonarqube/data/es6/nodes/0/node.lock
```
it seems to work fine.
