### ISSUE TITLE
$HOME is not set in some version of Docker

### ISSUE THREAD

**Issue by mplescano** [bitnami/bitnami-docker-sonarqube#24]
https://github.com/bitnami/bitnami-docker-sonarqube/blob/9d7f1587ccbab238078cd97280aecc1a11bb4dfd/7/debian-10/rootfs/app-entrypoint.sh#L7

Some versions of docker dont set the var env HOME so this script can fail. Therefore, its needed to set the line to the following:
export HOME=$(getent passwd $(whoami) | cut -d: -f6)
cd $HOME

**Comment by miguelaeh** [comment]
Hi @mplescano ,
Thank for reporting this, could you explain wich is the error you are getting and why it could be solved setting the home?

**Comment by mplescano** [comment]
The nami command needs to be in the HOME folder in order to locate the ".nami" folder.
if the nami command executes in the "/" folder, this gives an error saying: nami ERROR Cannot find any module matching the provided specification 'sonarqube'

**Comment by miguelaeh** [comment]
Hi @mplescano ,
I was able to reproduce the issue. We already created an internal task to work on adding the `HOME` to our nami containers.
As a workaround in the meantime, you can just set it to `HOME=/root` that is the correct one for the Sonarqube container.
Regards.

**Comment by marcosbc** [comment]
Hi @mplescano, we just released [`SonarQube 9.0.0-10-debian-10-r0`](https://github.com/bitnami/bitnami-docker-sonarqube#900-debian-10-r0) which includes major changes, and the source code is now available in the [`rootfs` folder](https://github.com/bitnami/bitnami-docker-sonarqube/tree/master/9/debian-10/rootfs) in this repo.

As part of these changes, the Nami tool is no longer used for the bootstrapping so this should not be an issue anymore. Therefore I'm proceeding to close this issue.
