### ISSUE TITLE
The deployed SonarQube container do not respond http pings on port: 9000 

### ISSUE THREAD

**Issue by cchen1987** [bitnami/bitnami-docker-sonarqube#25]
Hi!

I'm trying to deploy the SonarQube image (8.3.1) in an Azure App Service, and after the deployment, when the service tries to start the container, it fails with this error:

The docker command ran is the following:

"2020-06-17T18:28:00.425Z INFO - docker run -d -p 8225:9000 --name <my container name> -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITES_PORT=9000 -e WEBSITE_SITE_NAME=<my site name> -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=<the site host name> -e WEBSITE_INSTANCE_ID=<the site instance id> bitnami/sonarqube:8.3.1"

Log:
"2020-06-17T18:35:05.449Z ERROR - Container sonarqube-test-docker_0_5a4d763f didn't respond to HTTP pings on port: 9000, failing site start. See container logs for debugging."

¿Do someone know how to fix this?

Thanks in advance.

**Comment by marcosbc** [comment]
Hi @cchen1987, in your command I'm seeing that the container name is missing:

```diff
- --name -e WEBSITES_...
+ --name mycontainer -e WEBSITES_...
```

Also the DB credentials. Find an example of the required environment variables in the docker-compose.yml file: https://github.com/bitnami/bitnami-docker-sonarqube/blob/master/docker-compose.yml

**Comment by cchen1987** [comment]
Hi @marcosbc, sorry for answering so late, I finally found the problem, and it is the app service's problem, the available memory limit is under the necessary for elasticsearch.
And about the commands, I deleted the values of the environment variables for this issue, and that's why they're missing.

Thanks a lot for the help.
