### ISSUE TITLE
postgresql-persistence is wrong in documentation

### ISSUE THREAD

**Issue by joubbi** [bitnami/bitnami-docker-sonarqube#27]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

The instructions/examples in the README.md have a minor error, which has big consequences.
Both the template for docker-compose.yml and the example using the docker command line have this:
`/path/to/postgresql-persistence:/bitnami`.
It should be:
`/path/to/postgresql-persistence:/bitnami/postgresql`

The documentation here is correct:
https://github.com/bitnami/bitnami-docker-postgresql#persisting-your-database

**Describe the results you received:**

The persistent volume is not created. Killing the postgresql container makes all the changed in the database disappear.
When that happens you can't login on SonarQube until you remove the persistent volume for SonarQube.

There are no errors in the log so it's a bit tricky to find out about this problem until it is too late.

**Comment by juan131** [comment]
Hi @joubbi 

You're 100% correct. I just created a patch and the README.md will be updated in the following hours addressing this issue.

**Comment by juan131** [comment]
The README.md was updated a couple of weeks ago. I proceed to close the issue.
Feel free to reopen it if you require further assistance.
