### ISSUE TITLE
“bitnami” sonarqube developer edition docker image

### ISSUE THREAD

**Issue by shimuel** [bitnami/bitnami-docker-sonarqube#30]
**Description**
I asked this question [here ](https://community.bitnami.com/t/bitnami-sonarqube-developer-edition-docker-image/89661)but was directed here.

The sonarqube docker image basically pulls only community edition,

but I want to setup a "developer edition" for our organization's cicd/bitbucket integration needs and as most of our containers are bitnami based, would like to keep it the same for sonarqube

Can you please provide me info on how I can pull a "bitnami" sonarqube "developer edition" docker image to setup, as I don't see any information on this or how I can go about getting it setup.

I will be using docker-compose with bitnami Postgres 

Thanks

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**Docker  (docker-compose)

**Comment by miguelaeh** [comment]
Hi @shimuel ,
I am afraid we are right now packaging only the community edition, so it is not possible to pull the developer edition. Do you know which are the main differences between them?

**Comment by shimuel** [comment]
Thanks for the response, 
We are specifically looking at one specific feature - bitbucket integrations
Also, one other question, by how many versions the bitnami sonarquber image would be behind with the actual sonarqube counter parts, as when i pulled by the latest tag I got 7.9 version of sq ?

**Comment by miguelaeh** [comment]
Hi @shimuel ,
The latest version we are currently releasing is `8.5.1`. You can find it on GitHub: https://github.com/bitnami/bitnami-docker-sonarqube/tree/master/8/debian-10
And in dockerhub: https://hub.docker.com/r/bitnami/sonarqube/tags?page=1&ordering=last_updated
Could you share how are you testing that version?
