### ISSUE TITLE
How to start with docker  bitnami/sonarqube 7.5 ??

### ISSUE THREAD

**Issue by sky-daiji** [bitnami/bitnami-docker-sonarqube#31]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @sky-daiji, in the README we have a [TL;DR guide](https://github.com/bitnami/bitnami-docker-sonarqube#docker-compose) to get it up and running:

>### Docker Compose
>```console
>$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-sonarqube/master/docker-compose.yml
>$ docker-compose up
>```

You can customize it further via [Environment Variables](https://github.com/bitnami/bitnami-docker-sonarqube#environment-variables).

Let us know if there's anything else you'd like to know.
