### ISSUE TITLE
Error: 137 on docker

### ISSUE THREAD

**Issue by maurodouglas** [bitnami/bitnami-docker-sonarqube#33]
**Description**

Starting version 8-debian-10 with docker-compose don't start sonarqube

**Steps to reproduce the issue:**

1. [First Step]
    curl -LO https://github.com/bitnami/bitnami-docker-sonarqube/blob/8.7.0-debian-10-r10/8/debian-10/docker-compose.yml
   docker-compose up -d

result from tail on the .logs files

2021.03.10 14:51:54 INFO  web[][o.s.s.p.d.m.s.MassUpdate] 1 rows processed (0 items/sec)
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4124 'Populate 'reset_password' column with default value': success | time=266ms
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4125 'Make 'reset_password' column in 'users' table not nullable'...
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4125 'Make 'reset_password' column in 'users' table not nullable': success | time=255ms
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4126 'Secure gitlab secret parameters'...
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4126 'Secure gitlab secret parameters': success | time=178ms
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4200 'Move default project visibility to global properties'...
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4200 'Move default project visibility to global properties': success | time=272ms
2021.03.10 14:51:55 INFO  web[][DbMigrations] #4201 'Move default quality gate to global properties'...
2021.03.10 14:51:56 INFO  web[][DbMigrations] #4201 'Move default quality gate to global properties': success | time=284ms
2021.03.10 14:51:56 INFO  web[][DbMigrations] #4202 'Drop organization_uuid in table 'components''...
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4202 'Drop organization_uuid in table 'components'': success | time=1160ms
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4203 'Drop organization_uuid in table 'projects''...
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4203 'Drop organization_uuid in table 'projects'': success | time=206ms
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4204 'Drop organizations in table 'webhooks''...
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4204 'Drop organizations in table 'webhooks'': success | time=280ms
2021.03.10 14:51:57 INFO  web[][DbMigrations] #4205 'Drop table 'org_quality_gates''...
ERROR: 137

**Version**

- Output of `docker version`:

Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Output of `docker info`:

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 14
  Running: 13
  Paused: 0
  Stopped: 1
 Images: 21
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: pedjfebq9kepbk1apat7dyk9v
  Is Manager: true
  ClusterID: bafpze8im3sndwick5i4i3yf3
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 148.72.155.50
  Manager Addresses:
   148.72.155.50:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: usloft6141
 ID: JMZS:XLOV:P4ER:MPD7:VDJC:5RY3:6YED:WUK4:S67Y:UUCK:7TRM:P4XQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker inspect

[
    {
        "Id": "1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58",
        "Created": "2021-03-10T14:45:01.486549063Z",
        "Path": "/app-entrypoint.sh",
        "Args": [
            "nami",
            "start",
            "--foreground",
            "sonarqube"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2021-03-10T14:45:14.66522951Z",
            "FinishedAt": "2021-03-10T14:51:58.512218275Z"
        },
        "Image": "sha256:50b1d761c2f027705ef873c9f5d109abc74847179efee29552377e0ff8aca3d7",
        "ResolvConfPath": "/var/lib/docker/containers/1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58/hostname",
        "HostsPath": "/var/lib/docker/containers/1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58/hosts",
        "LogPath": "/var/lib/docker/containers/1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58/1b4bb2604c0cc3882feefa5edcca3a64653495ae9e1b5e470741a008d5650b58-json.log",
        "Name": "/sonarqube8_sonarqube_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "sonarqube8_sonarqube_data:/bitnami:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "sonarqube8_default",
            "PortBindings": {
                "9000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "59000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6408c0b561ecfb489ab9ab382304f7d020ce6e778ec8287fbf0d1eebe166bc03-init/diff:/var/lib/docker/overlay2/9614dce5ef719777e781fbf09a71a9fc02756335da84896db52bebc32ddd7f09/diff:/var/lib/docker/overlay2/943264262e22edbc8ec5e88932aeb818a3ec749bf9287b43949545a7d5fee9eb/diff:/var/lib/docker/overlay2/5bfb5dd2896716173ceee2ba1bec67106490b07ef711b789bce99c2fcec38ba2/diff:/var/lib/docker/overlay2/3dcc612cee704c071b42dce7172596e10b522543dbf51d138696a6cbcb24b0f7/diff:/var/lib/docker/overlay2/d52ee8d0a71b6bc3897adf56b0b325778d4bce1061bd928b6399ee6fe6a58bbf/diff:/var/lib/docker/overlay2/0e9f94172c735adbf8d7e0de90f7e4855ffbfc6915e8e6b30a52bcf534c7f6a4/diff:/var/lib/docker/overlay2/b99dc0c522ae1a22d1e3960db435d2a96518cba492c5afd917f826131fcd6683/diff:/var/lib/docker/overlay2/a0479ce8e2f0675c5ae86ff5c22f46533246cd546502622485906157a5d63253/diff:/var/lib/docker/overlay2/a8f8723017d2da1a8d860f9c4fe06ca436063b6b2cc1f3234927ac4ac74f0cfc/diff:/var/lib/docker/overlay2/1f6a008497753107de17a68765251e2f97d1b285aadc3cdcaa2e180bdbd62b1d/diff:/var/lib/docker/overlay2/3f14eb5f73c2bd426debbb98629dc9bf624ff1df8729854cf5761780d5b7b95a/diff",
                "MergedDir": "/var/lib/docker/overlay2/6408c0b561ecfb489ab9ab382304f7d020ce6e778ec8287fbf0d1eebe166bc03/merged",
                "UpperDir": "/var/lib/docker/overlay2/6408c0b561ecfb489ab9ab382304f7d020ce6e778ec8287fbf0d1eebe166bc03/diff",
                "WorkDir": "/var/lib/docker/overlay2/6408c0b561ecfb489ab9ab382304f7d020ce6e778ec8287fbf0d1eebe166bc03/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "sonarqube8_sonarqube_data",
                "Source": "/var/lib/docker/volumes/sonarqube8_sonarqube_data/_data",
                "Destination": "/bitnami",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "1b4bb2604c0c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "POSTGRESQL_HOST=postgresql8",
                "POSTGRESQL_ROOT_USER=postgres",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube",
                "POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234",
                "SONARQUBE_DATABASE_NAME=bitnami_sonarqube",
                "SONARQUBE_DATABASE_USER=bn_sonarqube",
                "SONARQUBE_DATABASE_PASSWORD=bitnami1234",
                "PATH=/opt/bitnami/postgresql/bin:/opt/bitnami/java/bin:/opt/bitnami/common/bin:/opt/bitnami/sonarqube/bin/linux-x86-64/:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BITNAMI_APP_NAME=sonarqube",
                "BITNAMI_IMAGE_VERSION=8.7.0-debian-10-r10",
                "OS_ARCH=amd64",
                "OS_FLAVOUR=debian-10",
                "OS_NAME=linux",
                "POSTGRESQL_PORT_NUMBER=5432",
                "POSTGRESQL_ROOT_PASSWORD=",
                "SMTP_HOST=",
                "SMTP_PASSWORD=",
                "SMTP_PORT=",
                "SMTP_PROTOCOL=",
                "SMTP_USER=",
                "SONARQUBE_CE_JAVA_ADD_OPTS=",
                "SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS=",
                "SONARQUBE_ELASTICSEARCH_PORT_NUMBER=9001",
                "SONARQUBE_ENABLE_DEMO_DATA=no",
                "SONARQUBE_PASSWORD=bitnami",
                "SONARQUBE_PORT_NUMBER=9000",
                "SONARQUBE_PROPERTIES=",
                "SONARQUBE_START_TIMEOUT=300",
                "SONARQUBE_USERNAME=admin",
                "SONARQUBE_WEB_CONTEXT=/",
                "SONARQUBE_WEB_JAVA_ADD_OPTS="
            ],
            "Cmd": [
                "nami",
                "start",
                "--foreground",
                "sonarqube"
            ],
            "Image": "docker.io/bitnami/sonarqube:8-debian-10",
            "Volumes": {
                "/bitnami": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/app-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "20008151b7e05c109f5eefe4d73627ac686a8815a7ca81e928e5d26778c492af",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "sonarqube8",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/opt/sonarqube8",
                "com.docker.compose.service": "sonarqube",
                "com.docker.compose.version": "1.28.2",
                "maintainer": "Bitnami <containers@bitnami.com>"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "99a10b42401c7fa51e1b2321730e57a5b6a3eaa6db6b9ef8cbfa5050ae78fd96",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/99a10b42401c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "sonarqube8_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "1b4bb2604c0c",
                        "sonarqube"
                    ],
                    "NetworkID": "15c75a36f389f11fb75d57c4d0120377e3d5e835e2064e98344dd01fc028f6d2",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

Running on a Physical Machine;

version 7-debian-10 starts ok

**Comment by marcosbc** [comment]
Hi @maurodouglas, unfortunately I could not reproduce your issues.

Note that error 137 means SIGKILL so it is probable that your Docker host did not have enough free memory to deploy SonarQube, so the kernel killed the process. If you try in a machine with more memory, it should work just fine.

**Comment by maurodouglas** [comment]
Hi @marcosbc  thanks for the response, I also thought that was because of memory, but my machine has 32Gb of Ram and 24Gb of that it's free, and on the docker inspect the OOMKilled is false;
And the version 7-debian-10 it's running fine just any image of the version 8 gets me this error

**Comment by marcosbc** [comment]
Hi @maurodouglas, unfortunately I could not reproduce your issues.

What I did notice though, when launching in different machine using Ubuntu 20.04 in AWS, is that SonarQube now requires specific kernel settings: https://docs.sonarqube.org/latest/requirements/requirements/

Without those settings the app would get stuck at this point:

```
sonarqube_1   | sonarqu INFO  ==> Starting app...
```

And the `/opt/bitnami/sonarqube/logs/sonar.log` file contained these errors:

```
$ cat /opt/bitnami/sonarqube/logs/sonar.log
2021.03.12 12:09:57 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /opt/bitnami/sonarqube/logs/sonarqube.log
2021.03.12 12:10:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 78
2021.03.12 12:10:03 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.03.12 12:10:03 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

If you continue to find issues after increasing kernel settings, could you provide more info? I.e.:

- docker-compose logs
- contents of sonar.log
