### ISSUE TITLE
Upgrading from bitnami/sonarqube:7.9.5 to bitnami/sonarqube:8.7.1 fails

### ISSUE THREAD

**Issue by shimuel** [bitnami/bitnami-docker-sonarqube#34]
**Upgrading from bitnami/sonarqube:7.9.5 to bitnami/sonarqube:8.7.1 fails with - Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'authgithub', 'authsaml', 'ldap', 'scmgit', 'scmsvn'**

Currently using bitnami/sonarqube:7.9.5 image - community edition with Postgres database and with SAML configured. Stopped containers and changed to bitnami/sonarqube:8.7.1 did a docker-compose up,
The containers start but the web server stops with the following message.

sonar.log
```
2021.03.31 05:57:12 WARN  app[][startup] ################################################################################
2021.03.31 05:57:12 WARN  app[][startup] The database must be manually upgraded. Please backup the database and browse /setup. For more information: https://docs.sonarqube.org/latest/setup/upgrading
2021.03.31 05:57:12 WARN  app[][startup] ################################################################################
2021.03.31 05:57:12 ERROR app[][startup] Startup failed: Plugins can't be loaded. See web logs for more information
2021.03.31 05:57:12 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2021.03.31 05:57:13 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.03.31 05:57:13 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2021.03.31 05:57:13 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
```

web.log
```
2021.03.31 05:57:12 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'authgithub', 'authsaml', 'ldap', 'scmgit', 'scmsvn'
```
**But upgrades flawlessly when I use the image: sonarqube:8.8-community**

**Steps to reproduce the issue:**

1. Replicated a instance of the organization's instance of the sonarqube server using the backed up volumes and brought up the server modified the baseURL.
2. Shutdown the container - docker-compose down
3. modified the imge to  bitnami/sonarqube:8.7.1 in the docker-compose.yml
4. And did a docker-compose up -d

**Describe the results you received:**
Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'authgithub', 'authsaml', 'ldap', 'scmgit', 'scmsvn'

 SonarQube is stopped
**Describe the results you expected:**
```
2021.03.31 07:14:19 WARN  web[][o.s.s.p.DatabaseServerCompatibility] The database must be manually upgraded. **Please backup the database and browse /setup.** For more information: https://docs.sonarqube.org/latest/setup/upgrading
```
**Additional information you deem important (e.g. issue happens only occasionally):**
Tried other bitnami sonarqube versions too such as  8.7.1-debian-10-r13 or 8.7.0-debian-10-r16   still same result.

Currently using bitnami/sonarqube:7.9.5 image - community edition with Postgres database and SAML is configured

**Version**

- Output of `docker version`:

```
Docker version 19.03.11-ol, build 78418d7
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.11-ol
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.35-2025.400.9.el7uek.x86_64
 Operating System: Oracle Linux Server 7.9
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.779GiB
 Name: eds-in-sqb01
 ID: BWAM:BXTQ:52DF:MBNY:JRRV:IOVT:CXPP:URUD:F3IB:QSFQ:5DQK:QW4J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

[bitnami-web.log](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234608/bitnami-web.log)
[docker-compose-bitnami.txt](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234609/docker-compose-bitnami.txt)
[docker-compose-sonarqube-community.txt](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234610/docker-compose-sonarqube-community.txt)
[sonarqube-community-sonar.log](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234611/sonarqube-community-sonar.log)
[sonarqube-community-web.log](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234612/sonarqube-community-web.log)
[bitnami-sonar.log](https://github.com/bitnami/bitnami-docker-sonarqube/files/6234613/bitnami-sonar.log)

**Comment by shimuel** [comment]
Hi, thanks for the quick response, appreciate it.

It looks to be an issue specific to bitnami/sonarqube images only.

As I mentioned earlier and included log(s), 
I was able to able upgrade from  bitnami/sonarqube:7.9.5 ---> sonarqube:8.8-community (included the log for this too earlier) so there was no issues I faced. 

Also, did read through the [docs ](https://docs.sonarqube.org/latest/setup/upgrading/)and compatibility [matrix ](https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/)on 

but bitnami/sonarqube:7.9.5  to  bitnami/sonarqube:8.7.1 or  bitnami/sonarqube:anything fails ?

Can you please clarify, this upgrade will not work ?

**Comment by javsalgar** [comment]
Hi,

It seems that you may need to do some manual steps disabling some incompatible plugins.

```
2021.03.31 05:57:12 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'authgithub', 'authsaml', 'ldap', 'scmgit', 'scmsvn'
```

You would need to start a container mounting the sonarqube volume, go to the plugins section and remove these plugins that are not compatible anymore. That may partially fix the upgrade issue.

**Comment by shimuel** [comment]
Thanks was able to upgrade by first removing all installed plugins and then changing the docker-compose.yml from sonarqube version from 7.9.5 to 8+ and trigger the upgrade DB step by  sonarqubeURL/setup .

Thanks
