### ISSUE TITLE
Bad mapping of uid and gid for user sonarqube

### ISSUE THREAD

**Issue by adrianmusante** [bitnami/bitnami-docker-sonarqube#41]
I want to upgrade the SonarQube version from 8.9.0 to 9.0.1 but I am having a problem with the non-root user. The user sonarqube in the latest version is being created as 999:999 (uid:gid).

I read your [documentation ](https://github.com/bitnami/bitnami-docker-sonarqube#900-debian-10-r0) where it indicates that from version 9 both the daemon and the container will use the same user. 

> The SonarQube container image has been migrated to a "non-root" user approach. Previously the container ran as the root user and the SonarQube daemon was started as the **sonarqube** user. From now on, both the container and the SonarQube daemon run as user **1001**. 

I compared the users between the versions and I could find that before the user was created as 1001:1001 and now with 999:999. The container in the last version uses a non-mapped user with value 1001:0. 

In conclusion, I think that the users used by the daemon and the container should use the sonarqube user mapped as 1001: 1001. Is this correct?

---

### 8.9.0

**Digest:** bitnami/sonarqube@sha256:7eecd5b0e332ffd1e823b2e4454c0d9dee489985b2cdc93983886b5aacbdd2dd 

```sh
root@e977a4ea3db6:/# id
uid=0(root) gid=0(root) groups=0(root)

root@e977a4ea3db6:/# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
bitnami:x:1000:1000::/home/bitnami:/bin/bash
sonarqube:x:1001:1001::/home/sonarqube:/bin/sh
```

### 9.0.1

**Digest:** bitnami/sonarqube@sha256:a657ae7543a41af1049799453666c38df76b85e19deaa5626a24b62d4b9c5ea0

```sh
I have no name!@9d96d463f194:/$ id
uid=1001 gid=0(root) groups=0(root)

I have no name!@9d96d463f194:/$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
sonarqube:x:999:999::/home/sonarqube:/bin/sh
```

**Comment by yilmi** [comment]
Hi @adrianmusante,.

We do indeed run the latest container as user 1001 but I , if you look at the processes running, they all map to user 1001:
```bash
❯ docker exec -u root -it bitnami-docker-sonarqube_sonarqube_1 ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001           1  0.0  0.0   2392  1664 ?        Ss   12:01   0:00 /bin/sh /opt/
1001         908  0.0  0.0  12244  1160 ?        Sl   12:02   0:03 /opt/bitnami/
1001         910  0.3  0.5 5056324 98328 ?       Sl   12:02   0:12 java -Dsonar.
1001         945  0.8  4.8 7143252 799176 ?      Sl   12:02   0:30 /opt/bitnami/
1001        1070  1.1  2.4 6492744 398664 ?      Sl   12:02   0:41 /opt/bitnami/
1001        1160  0.6  1.6 5318144 267372 ?      Sl   12:02   0:23 /opt/bitnami/
root        1253  0.0  0.0   7644  2800 pts/0    Rs+  13:03   0:00 ps aux
```

I also see the /etc/passwd uid/gid change, could you give a bit more details with regards to the issue you're having?

**Comment by adrianmusante** [comment]
Hi @yilmi

Thats correct, the process runs as user 1001 but this user is generated by command [USER ](https://github.com/bitnami/bitnami-docker-sonarqube/blob/e85873d922994dc9ce074c7870a788d8db96e205/9/debian-10/Dockerfile#L33) as 1001:0.

```sh
I have no name!@a837d2673d22:/tmp$ touch test
I have no name!@a837d2673d22:/tmp$ ls -lAh
total 0
-rw-r--r-- 1 1001 root 0 Sep 20 14:27 test
I have no name!@a837d2673d22:/tmp$ id -u sonarqube
999
I have no name!@a837d2673d22:/tmp$ id -G sonarqube
999
```

When I run the container skipping the entrypoint the sonarqube user is not created. I think 999 is assigned because 1001 is already taken by the user who runs the container. Maybe, the user should be created before calling the USER command.

I thought i was having trouble writing to the volume and started researching the difference between the users. Although it seems strange to me the way that are being created. It seemed appropriate to report it.
You feel free to close the incident if you don't feel that is a issue. Thank you very much for your quickly attention.

**Comment by yilmi** [comment]
Hi @adrianmusante, thanks, let me check a couple of things before coming getting back to you 👍

**Comment by yilmi** [comment]
Hi @adrianmusante, I was able to reproduce the issue, would you like to submit a contribution to fix this issue?

**Comment by adrianmusante** [comment]
Hi @yilmi. Yes, I will try to make a pull request in this week. 

Many thanks
