### ISSUE TITLE
hostname rds.domainname.app could not be resolved - Could not connect to the database 

### ISSUE THREAD

**Issue by ThreatACC** [bitnami/bitnami-docker-sonarqube#43]
**Description**

Unable to connect to existing RDS database.
**Steps to reproduce the issue:**

1. Pull helm chart from repo
2. Edited values yaml -
   Service:
       Type: ClusterIP
 externalDatabase:
  host: rds.domainname.app
  user: ourusername
  password: dbpassword
  database: dbname
  port: 5432

**Describe the results you received:**
Logs from K8

sonarqube 16:12:08.65 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars                                                                                    │
│ sonarqube 16:12:08.69 WARN  ==> Hostname "rds.domainname.app" could not be resolved, this could lead to connection issues                                         │
│ sonarqube 16:12:08.69 INFO  ==> Creating SonarQube configuration                                                                                                       │
│ sonarqube 16:12:08.74 INFO  ==> Trying to connect to the database server                                                                                               │
│ sonarqube 16:13:08.85 ERROR ==> Could not connect to the database

I was hopping to connect to database and start testing things :)

**Comment by javsalgar** [comment]
Hi,

Looking at this 

```
│ sonarqube 16:12:08.69 WARN ==> Hostname "rds.domainname.app" could not be resolved, this could lead to connection issues │
```

It seems that there could be a DNS issue in the cluster. Could you try running with BITNAMI_DEBUG=true? `image.debug=true` in the values.yaml file.

**Comment by ThreatACC** [comment]
We resolved it - 
turn out it deprecated and we should have used `jdbcOverwrite`
Thanks
