### ISSUE TITLE
Cannot start bitnami/sonarqube:latest

### ISSUE THREAD

**Issue by JensBeutel** [bitnami/bitnami-docker-sonarqube#45]
### Name and Version

bitnami/sonarqube:9.3

### What steps will reproduce the bug?

1. linux desktop with docker version 20.10.12
2. vs.map, fs-file, ulimit -n and -u are on set on the host like in the description from issue #40 
4. start container with docker-compose file

docker-compose.yaml with removed credentials

```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=
      - POSTGRESQL_USERNAME=
      - POSTGRES_PASSWORD=
      - POSTGRESQL_DATABASE=
  sonarqube:
    image: docker.io/bitnami/sonarqube:latest
    ports:
      - '80:9000'
    depends_on:
      - postgresql
    volumes:
      - 'sonarqube_data:/bitnami/sonarqube'
    environment:
      - BITNAMI_DEBUG=true
      - SONARQUBE_USERNAME=
      - SONARQUBE_PASSWORD=
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=
      - SONARQUBE_DATABASE_PASSWORD=
      - SONARQUBE_DATABASE_NAME=
volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
```

### What is the expected behavior?

sonarqube should start

### What do you see instead?

crashes after 300 tries of "Entry "SonarQube is up" still not present

### Additional information

```
**examanination of the es.log during startup.**

INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/bitnami/sonarqube/temp\
INFO app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:44061]
INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/bitnami/sonarqube/elasticsearch]: /opt/bitnami/sonarqube/elasticsearch/bin/elasticsearch
 INFO app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
uncaught exception in thread [main]
 java.security.AccessControlException: access denied ("java.io.FilePermission" "/sys/fs/cgroup/../../cpu90/cpu.stat" "read")
```

Additional info:

The cpu.stat file is located under `/sys/fs/cgroup/cpu.stat`. cpu90-directory does not exist

**Comment by juan131** [comment]
Hi @JensBeutel 

It looks like a permissions issue. This is a [non-root container](https://github.com/bitnami/bitnami-docker-sonarqube#why-use-a-non-root-container) by default and, as it's explained in the section ["Persisting your application"](https://github.com/bitnami/bitnami-docker-sonarqube#persisting-your-application):

> As this is a non-root container, the mounted files and directories must have the proper permissions for the UID `1001`.

Are you able to reproduce the issue if you remove the "sonarqube_data" volume?

**Comment by JensBeutel** [comment]
Hi @juan131

thank your for your quick response. I tried it without a volume. Unfortunately, the error persists.

**Comment by juan131** [comment]
Hi @JensBeutel 

It's probably not related with system permissions but Kernel settings. ElasticSearch (included as a bundled component in SonarQube) requires certain Kernel settings to be configured in the host machine you're using to run the containers. That's the reason why we added in the SonarQube char the possibility of running a privileged ini-container that adapts the kernel, see:

- https://github.com/bitnami/charts/tree/master/bitnami/sonarqube#sysctl-image-parameters

This init-container executes a piece of code like the one below to adapt the Kernel settings:

```bash
if [[ 262144 -gt $(sysctl -n vm.max_map_count) ]]; then
    sysctl -w vm.max_map_count=262144
fi
if [[ 65536 -gt $(sysctl -n fs.file-max) ]]; then
    sysctl -w fs.file-max=65536
fi
```

**Comment by JensBeutel** [comment]
Hi @juan131,

I already set the values on the host according to the documentation plus ulimit -n and -u as mentioned in #40.

However, your assumption seems to be right. I tested the exact same docker-compose file on Windows with docker-desktop. After the change of vm.max_map_count and fs.file_max in wsl everything works perfect.

I tried to launch the bitnami/elasticsearch container to make sure, that these values are set correctly. This container worked like a charme. 
At this point I am quite confused because if the docker-compose file is wrong it wouldn't run on windows. If the kernel settings on the linux system did not fit the needs, the elasticsearch container would fail, right?

**Comment by juan131** [comment]
Hi @JensBeutel 

I'm glad that it worked after adapting the Kernel settings.

>  If the kernel settings on the linux system did not fit the needs, the elasticsearch container would fail, right?

In theory: yes. Probably with a different error but it should fail. Did you try using the same ElasticSearch version used in SonarQube?

**Comment by JensBeutel** [comment]
Hey @juan131 
Good point. For the first test I used the latest version. After your comment I tried version 7.16.3 from elasticsearch. This version worked as well.

I also tried another approach to get rid of the problem. In the elasticsearch java opts variable I add -Dbootstrap.system_call_filter=false. This should disable the seccomp filter. However, it didn't changed anything. The same error message appears.

**Comment by JensBeutel** [comment]
It is not a solution for my problem but it brings me a step further to the core issue. I tried the official sonarqube image without any additional environment variables (except the volumes) and now I have a running sonarqube instance. So in conclusion I guess you are right. The problem seems to be that the bitnami image is a non root image. I have to configure my host system probably to get it work but this not a bug/problem with this image. Thank you for you help @juan131. You can close the issue if you want

**Comment by juan131** [comment]
Hi @JensBeutel 

Thanks so much for sharing your insights! I'm very glad that you could workaround the issue.
