### ISSUE TITLE
Cannot install gitlab-auth plugin

### ISSUE THREAD

**Issue by m2nlight** [bitnami/bitnami-docker-sonarqube#6]
1. goto marketplace page
2. search gitlab-auth plugin and install it
3. restart sonarqube

sonarqube cannot start web server.

When I remove GitLab Auth plug-in jar file by 'docker exec' or local mapping file location:

1. Docker-compose restart stilling failure
2. Docker-compose down, then up -d, the SonarQube web started ok.

**Comment by marcosbc** [comment]
Hi @m2nlight, we were able to reproduce this issue. SonarQube is stopping but not starting properly, with this error:

```
2019.02.21 14:35:41 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: The property 'sonar.web.port' is not an int value: For input string: ""
	at org.sonar.api.config.Configuration.getInt(Configuration.java:142)
	at org.sonar.server.platform.UrlSettings.computeBaseUrl(UrlSettings.java:70)
	at org.sonar.server.platform.UrlSettings.getBaseUrl(UrlSettings.java:54)
	at org.sonar.server.platform.ServerImpl.getPublicRootUrl(ServerImpl.java:86)
(...)
```

And when checking `sonar.properties`, the value of this property is empty:

```
# TCP port for incoming HTTP connections. Default value is 9000.
sonar.web.port =
```

After that we can get SonarQube up and running with:

```
nami restart sonarqube
```

We'll investigate further and update with any progress.

**Comment by m2nlight** [comment]
The error is can't load plugin.
We are work in CentOS 7 and an latest docker-ce. 
And official SonarQube no this error.

**Comment by marcosbc** [comment]
We're aware of that @m2nlight, unfortunately we have not had time to look into this issue yet. We will update this issue once we start working on this.

**Comment by marcosbc** [comment]
Hi @m2nlight, we released a new revision of SonarQube yesterday which fixes the issue you mention. Could you try again and confirm it's fixed?

**Comment by m2nlight** [comment]
Hi @marcosbc 
It's worked! Good job!
Thanks
