### ISSUE TITLE
Manual install on EC2 unaccessible

### ISSUE THREAD

**Issue by shumyster** [bitnami/bitnami-docker-sonarqube#7]
**Description**
After manual steps to run the sql and SQ containers, the SQ container is inaccessible on port 9000.

**Steps to reproduce the issue:**

Followed the step-by-step instructions in the readme.

 1.   Create a network

    sudo docker network create sonarqube-tier

 2.   Create a volume for PostgreSQL persistence and create a PostgreSQL container

    sudo docker volume create --name postgresql_data
    sudo docker run -d --name postgresql \
     -e ALLOW_EMPTY_PASSWORD=yes \
     -e POSTGRESQL_USERNAME=bn_sonarqube \
     -e POSTGRESQL_DATABASE=bitnami_sonarqube \
     -e POSTGRESQL_PASSWORD=bitnami1234 \
     --net sonarqube-tier \
     --volume postgresql_data:/bitnami \
     bitnami/postgresql:latest

3.    Create volumes for SonarQube persistence and launch the container

    sudo docker volume create --name sonarqube_data
    sudo docker run -d --name sonarqube -p 80:9000 \
     -e ALLOW_EMPTY_PASSWORD=yes \
     -e SONARQUBE_DATABASE_USER=bn_sonarqube \
     -e SONARQUBE_DATABASE_NAME=bitnami_sonarqube \
     -e SONARQUBE_DATABASE_PASSWORD=bitnami1234 \
     --net sonarqube-tier \
     --volume sonarqube_data:/bitnami \
     bitnami/sonarqube:latest

4.    Access your application at http://your-ip:9000 --=> Inaccessible

--------------------------------------------------------------
**Describe the results you received:**

SQ container stays up for 5 minutes then stops. kept it up with -it but still no access

**Describe the results you expected:**

Login page accessible.

**Additional information you deem important (e.g. issue happens only occasionally):**

>> Docker engine runs on an EC2 ubuntu instance, alongside Jenkins (Jenkins not on a container).
Jenkins is accessible. Routing to EC2 works, and subnet inbound rules as well as security group rules allow ports 9000 and 5432 in.

>> when both containers (SQL and SQ) are up I can see that the custom network assigns 2 IP addresses to them on the 172.18/16 subnet, which seems ok.
When I telnet the SQL IP on the 172.18/16 subnet on port 5432 I see the port is open.
when I telnet the SQ IP on the 172.18/16on port 9000 or 80 the connection is refused.
When I telnet localhost on port 5432, 9000, or 80, connections are refused.

**Version**

docker -v
Docker version 18.06.1-ce, build e68fc7a

--------------------------------------------------------------

#> sudo docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1032-aws
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851GiB
Name: ip-10-0-10-4
ID: XAYD:N3MW:G35U:XG3I:ISIS:4CCU:RA3I:NXSR:PNFW:KUP2:CFUP:LPWD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

EC2 instance with Ubuntu 18.04 on it, running local install of Jenkins and Docker enginer.

**Comment by javsalgar** [comment]
Hi,

Could you let us know what the logs show?

**Comment by shumyster** [comment]
Checked the logs and noticed an issue with insufficient system resources. 
I changed the EC2 to a larger container type and the container came up and stayed up.
The access tho, based on the port publishing is 80, not 9000, so http://<EC2_instance_public_IP>, not http://<EC2_instance_public_IP>:9000 as the instructions mention.

Thanks for pointing me in the right direction.
cheers.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know :) If you find any other issues, do not hesitate to open a new ticket
