### ISSUE TITLE
ERROR Cannot find any module matching the provided specification 'sonarqube'

### ISSUE THREAD

**Issue by asiekkowa** [bitnami/bitnami-docker-sonarqube#8]
I tried to run docker image with sonar on OpenShift, tested tags: 7.7.0, 7.6.0, 7.7.0-debian-9-r14

```
  |  
-- | --
  | Welcome to the Bitnami sonarqube container
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
  |  
  | INFO  ==> Starting sonarqube...
  | nami    ERROR Cannot find any module matching the provided specification 'sonarqube'
```

Environment:
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
docker 1.13.1

**Comment by javsalgar** [comment]
Hi,

I think this has to do of the non-root nature of Openshift. Currently, the Sonarqube container is not prepared to work as non-root. We will update this thread when the container is available as non-root.
